// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: watec/shares/free.proto

package freepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Free struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Free) Reset() {
	*x = Free{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watec_shares_free_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Free) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Free) ProtoMessage() {}

func (x *Free) ProtoReflect() protoreflect.Message {
	mi := &file_watec_shares_free_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Free.ProtoReflect.Descriptor instead.
func (*Free) Descriptor() ([]byte, []int) {
	return file_watec_shares_free_proto_rawDescGZIP(), []int{0}
}

func (x *Free) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Free) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_watec_shares_free_proto protoreflect.FileDescriptor

var file_watec_shares_free_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x61, 0x74, 0x65, 0x63, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2f, 0x66,
	0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x77, 0x61, 0x74, 0x65, 0x63,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x66, 0x72, 0x65, 0x65, 0x22, 0x2a, 0x0a, 0x04,
	0x46, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x72, 0x6e, 0x6f, 0x65, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x77, 0x61, 0x74, 0x65, 0x63, 0x2f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x73, 0x2f, 0x66, 0x72, 0x65, 0x65, 0x3b, 0x66, 0x72, 0x65, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_watec_shares_free_proto_rawDescOnce sync.Once
	file_watec_shares_free_proto_rawDescData = file_watec_shares_free_proto_rawDesc
)

func file_watec_shares_free_proto_rawDescGZIP() []byte {
	file_watec_shares_free_proto_rawDescOnce.Do(func() {
		file_watec_shares_free_proto_rawDescData = protoimpl.X.CompressGZIP(file_watec_shares_free_proto_rawDescData)
	})
	return file_watec_shares_free_proto_rawDescData
}

var file_watec_shares_free_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_watec_shares_free_proto_goTypes = []interface{}{
	(*Free)(nil), // 0: watec.shares.free.Free
}
var file_watec_shares_free_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_watec_shares_free_proto_init() }
func file_watec_shares_free_proto_init() {
	if File_watec_shares_free_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watec_shares_free_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Free); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watec_shares_free_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watec_shares_free_proto_goTypes,
		DependencyIndexes: file_watec_shares_free_proto_depIdxs,
		MessageInfos:      file_watec_shares_free_proto_msgTypes,
	}.Build()
	File_watec_shares_free_proto = out.File
	file_watec_shares_free_proto_rawDesc = nil
	file_watec_shares_free_proto_goTypes = nil
	file_watec_shares_free_proto_depIdxs = nil
}
